"""Fix is_accomplished 2

Revision ID: 26cd66a2fe33
Revises: f0d85c7e3006
Create Date: 2020-06-10 21:45:27.865540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26cd66a2fe33'
down_revision = 'f0d85c7e3006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_accomplished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_accomplished', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
