"""Fix is_accomplished 4

Revision ID: e6f324f3acc6
Revises: 1f9ea3208db1
Create Date: 2020-06-10 21:46:50.571877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f324f3acc6'
down_revision = '1f9ea3208db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_accomplished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_accomplished', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
