"""Fix is_accomplished

Revision ID: f0d85c7e3006
Revises: 7ed3340c750b
Create Date: 2020-06-10 21:17:38.328756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d85c7e3006'
down_revision = '7ed3340c750b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_accomplished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_accomplished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
