"""Add is_accomplished again

Revision ID: f4c467b13c23
Revises: e59393715f23
Create Date: 2020-06-10 21:51:14.040826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c467b13c23'
down_revision = 'e59393715f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_done', sa.Boolean(), nullable=True))
    op.drop_column('task', 'is_accomplished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_accomplished', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('task', 'is_done')
    # ### end Alembic commands ###
